public protocol Statement: Wrapper  {
    
    func executeQuery(sql: String) throws -> ResultSet
    func executeUpdate(sql: String) throws -> Int
    func close() throws
    
    func getMaxFieldSize() throws -> Int
    func setMaxFieldSize(max: Int) throws
    
    func getMaxRows() throws -> Int
    func setMaxRows(max: Int) throws
    
    func setEscapeProcessing(enable: Bool) throws
    
    func getQueryTimeout() throws -> Int
    func setQueryTimeout(seconds: Int) throws
    
    func cancel() throws
    
    func getWarnings() throws -> SQLWarning
    func clearWarnings() throws
    
    func setCursorName(name: String) throws
    
    func execute(sql: String) throws -> Bool
    
    func getResultSet() throws -> ResultSet
    func getUpdateCount() throws -> Int
    func getMoreResults() throws -> Bool
    
    func setFetchDirection(direction: Int) throws
    func getFetchDirection() throws -> Int
    
    func setFetchSize(rows: Int) throws
    func getFetchSize() throws -> Int
    
    func getResultSetConcurrency() throws -> Int
    func getResultSetType() throws -> Int
    
    func addBatch(sql: String) throws
    func clearBatch() throws
    func executeBatch() throws -> [Int]
    
    func getConnection() throws -> Connection
    
    //  var CLOSE_CURRENT_RESULT: Int = 1
    // var KEEP_CURRENT_RESULT: Int = 2
    // var CLOSE_ALL_RESULTS: Int = 3
    // var SUCCESS_NO_INFO: Int = -2
    // var EXECUTE_FAILED: Int = -3
    // var RETURN_GENERATED_KEYS: Int = 1
    // var NO_GENERATED_KEYS: Int = 2
    
    func getMoreResults(current: Int) throws -> Bool
    
    func getGeneratedKeys() throws -> ResultSet
    
    func executeUpdate(sql: String, autoGeneratedKeys: Int) throws -> Int
    func executeUpdate(sql: String, columnIndexes: [Int]) throws -> Int
    func executeUpdate(sql: String, columnNames: [String]) throws -> Int
    
    func execute(sql: String, autoGeneratedKeys: Int) throws -> Bool
    func execute(sql: String, columnIndexes: [Int]) throws -> Bool
    func execute(sql: String, columnNames: [String]) throws -> Bool
    
    func getResultSetHoldability() throws -> Int
    
    func isClosed() throws -> Bool
    
    func setPoolable(poolable: Bool) throws
    func isPoolable() throws -> Bool
    
    func closeOnCompletion() throws
    func isCloseOnCompletion() throws -> Bool
    
    // No Impl
    func getLargeUpdateCount() throws -> Int64
    func setLargeMaxRows(max: Int64) throws
    func getLargeMaxRows() throws -> Int64
    
    // long[] executeLargeBatch()
    func executeLargeBatch() throws -> [Int64]
    func executeLargeUpdate(sql: String) throws -> Int64
    func executeLargeUpdate(sql: String, autoGeneratedKeys: Int) throws -> Int64
    func executeLargeUpdate(sql: String, columnIndexes: [Int]) throws -> Int64
    func executeLargeUpdate(sql: String, columnNames: [String]) throws -> Int64
    
    // TODO: add enquote
    
}
